### ISSUE TITLE
Error in Brute-Force parallel processing on an AMD server

### ISSUE THREAD

**Issue by wariobrega** [mazzalab/pyntacle#15] opened 2018-10-10 16:30 UTC
When running the following command:
`pyntacle keyplayer kp-finder -I brute-force -i NCEAS_carpinteria.adjm  -k 2 -m 1 -d ./ -T 32`
on a 48-core AMD server, I get the following error  when Pyntacle computes dF: 

`Terminating: fork() called from a process already using GNU OpenMP, this is unsafe.`

**Comment by mazzalab** [comment] 2020-06-25 07:31
The problem was caused by the concurrent execution of processes and threads that saturated the computing capabilities. It will be fixed in version 1.2, where this is disabled from the command-line, yet possible by using the APIs.

**Closed by mazzalab** 2020-06-25 07:31 UTC
